<?php

if (!defined('BASEPATH'))
	exit('No direct script access allowed');

class Adminlogin extends CI_Controller
{

	function __construct()
	{
		parent::__construct();
		$this->load->model('Madmin');
	}

	function index()
	{
		$this->load->view('templatelogin');
	}

	function aksi_login()
	{
		$username = $this->input->post('username');
		$password = $this->input->post('password');
		$where = array(
			'username' => $username,
			'password' => $password
		);
		$cek = $this->Madmin->cek_login("admin", $where)->num_rows();
		if ($cek > 0) {

			$data_session = array(
				'username' => $username,
				'status' => "login"
			);

			$this->session->set_userdata($data_session);

			redirect(base_url("home"));
		} else {
			echo "Username dan password salah !";
		}
	}

	function logout()
	{
		$this->session->sess_destroy();
		redirect(base_url('adminlogin'));
	}
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */